spring.application.name=TaskProject
server.port=8193

# DataSource Configuration
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/TaskProject?createDatabaseIfNotExist=true
spring.datasource.username=XXXXXX
spring.datasource.password=XXXXXX

# JPA Configuration
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
